"use client";

import Link from "next/link";
import { BarChart3, ExternalLink } from "lucide-react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Cell,
  LabelList,
} from "recharts";

export interface ServiceReportsChartProps {
  data: { year: string; Delivered: number }[];
  selectedYear: string;
  /** Clicking a year bar updates the dashboard year filter when provided. */
  onYearChange?: (year: string) => void;
}

const SELECTED_FILL = "#2a7797";
const OTHER_FILL = "#4ec2bb";

export function ServiceReportsChart({
  data,
  selectedYear,
  onYearChange,
}: ServiceReportsChartProps) {
  const total = data.reduce((sum, row) => sum + row.Delivered, 0);
  const selectedCount =
    data.find((row) => row.year === selectedYear)?.Delivered ?? 0;
  const maxValue = data.reduce(
    (max, row) => Math.max(max, row.Delivered),
    0,
  );
  const yMax = Math.max(4, Math.ceil(maxValue * 1.15));
  const trackerHref =
    selectedYear && selectedYear !== "all"
      ? `/dashboard/services/tracker?year=${selectedYear}`
      : "/dashboard/services/tracker";

  return (
    <div className="md:col-span-2 bg-surface border border-slate-300/70 rounded-[24px] p-6 shadow-[0_20px_40px_rgba(15,23,42,0.1)] flex flex-col">
      <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3 mb-5 font-quicksand">
        <div className="min-w-0 space-y-1">
          <div className="flex items-center gap-2 text-[#2a7797]">
            <BarChart3 className="w-4 h-4 shrink-0" />
            <h3 className="text-xs font-extrabold uppercase tracking-wider">
              Service Reports Generated by Year
            </h3>
          </div>
          <p className="text-[11px] text-slate-400 font-aileron pl-6">
            Analyses with an uploaded or linked service report
          </p>
        </div>

        <Link
          href={trackerHref}
          className="flex items-center gap-1.5 self-start text-[11px] font-bold text-[#2a7797] bg-[#e6f4f8] hover:bg-[#d5eff6] transition-colors duration-200 px-3 py-1.5 rounded-xl border border-[rgba(42,119,151,0.25)] shadow-[0_4px_10px_rgba(15,23,42,0.04)]"
        >
          <span>Open Tracker</span>
          <ExternalLink className="w-3 h-3" />
        </Link>
      </div>

      {data.length === 0 ? (
        <div className="h-64 flex items-center justify-center text-sm text-slate-400 font-aileron">
          No service reports generated yet
        </div>
      ) : (
        <>
          <div className="grid grid-cols-2 gap-3 mb-5">
            <div className="rounded-2xl border border-slate-200/80 bg-slate-50/70 px-4 py-3">
              <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 font-quicksand">
                All years
              </p>
              <p className="mt-1 text-2xl font-black tracking-tight text-slate-800 font-aileron">
                {total}
              </p>
            </div>
            <div className="rounded-2xl border border-[rgba(42,119,151,0.22)] bg-[#e6f4f8]/70 px-4 py-3">
              <p className="text-[10px] font-bold uppercase tracking-wider text-[#2a7797] font-quicksand">
                {selectedYear}
              </p>
              <p className="mt-1 text-2xl font-black tracking-tight text-[#174e64] font-aileron">
                {selectedCount}
              </p>
            </div>
          </div>

          <div className="w-full h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart
                data={data}
                margin={{ top: 18, right: 8, left: -12, bottom: 4 }}
                barCategoryGap="28%"
              >
                <CartesianGrid
                  strokeDasharray="3 3"
                  vertical={false}
                  stroke="#e2e8f0"
                />
                <XAxis
                  dataKey="year"
                  axisLine={false}
                  tickLine={false}
                  tick={{
                    fill: "#64748b",
                    fontSize: 12,
                    fontWeight: 700,
                    fontFamily: "Quicksand, sans-serif",
                  }}
                />
                <YAxis
                  allowDecimals={false}
                  domain={[0, yMax]}
                  axisLine={false}
                  tickLine={false}
                  width={36}
                  tick={{
                    fill: "#94a3b8",
                    fontSize: 11,
                    fontFamily: "Quicksand, sans-serif",
                  }}
                />
                <Tooltip
                  cursor={{ fill: "rgba(42, 119, 151, 0.06)", radius: 8 }}
                  wrapperStyle={{ fontFamily: "Aileron, sans-serif", zIndex: 50 }}
                  contentStyle={{
                    backgroundColor: "#fff",
                    borderRadius: "12px",
                    border: "1px solid #e2e8f0",
                    padding: "8px 12px",
                    boxShadow: "0 10px 25px rgba(15,23,42,0.08)",
                  }}
                  labelStyle={{
                    fontSize: "12px",
                    fontWeight: 700,
                    color: "#64748b",
                    marginBottom: "2px",
                  }}
                  formatter={(value) => [
                    `${Number(value ?? 0)} ${Number(value ?? 0) === 1 ? "report" : "reports"}`,
                    "Generated",
                  ]}
                />
                <Bar
                  dataKey="Delivered"
                  name="Reports"
                  radius={[10, 10, 4, 4]}
                  maxBarSize={44}
                  cursor={onYearChange ? "pointer" : "default"}
                  onClick={(entry) => {
                    const year = (entry as { year?: string })?.year;
                    if (year && onYearChange) onYearChange(year);
                  }}
                >
                  {data.map((entry) => {
                    const isSelected = entry.year === selectedYear;
                    return (
                      <Cell
                        key={`sr-year-${entry.year}`}
                        fill={isSelected ? SELECTED_FILL : OTHER_FILL}
                        fillOpacity={isSelected ? 1 : 0.55}
                        stroke={isSelected ? "#1f5c76" : "transparent"}
                        strokeWidth={isSelected ? 1.5 : 0}
                      />
                    );
                  })}
                  <LabelList
                    dataKey="Delivered"
                    position="top"
                    offset={8}
                    className="fill-slate-600 text-[11px] font-bold"
                    formatter={(value) =>
                      Number(value) > 0 ? String(value) : ""
                    }
                  />
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>

          <div className="mt-3 flex flex-wrap items-center justify-between gap-2">
            <div className="flex items-center gap-4 text-[11px] font-semibold text-slate-500 font-aileron">
              <span className="inline-flex items-center gap-1.5">
                <span
                  className="h-2.5 w-2.5 rounded-sm"
                  style={{ backgroundColor: SELECTED_FILL }}
                />
                Selected year
              </span>
              <span className="inline-flex items-center gap-1.5">
                <span
                  className="h-2.5 w-2.5 rounded-sm opacity-55"
                  style={{ backgroundColor: OTHER_FILL }}
                />
                Other years
              </span>
            </div>
            {onYearChange ? (
              <p className="text-[11px] text-slate-400 font-quicksand">
                Click a bar to filter the overview by that year
              </p>
            ) : null}
          </div>
        </>
      )}
    </div>
  );
}
