import type { Metadata } from "next";
import { Geist, Geist_Mono, Quicksand } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  variable: "--font-quicksand-mono",
  subsets: ["latin"],
});

const aileron = localFont({
  src: [
    {
      path: "../public/fonts/AILERON-BLACK.OTF",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/AILERON-BLACKITALIC.OTF",
      weight: "900",
      style: "italic",
    },
    {
      path: "../public/fonts/AILERON-BOLD.OTF",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/AILERON-BOLDITALIC.OTF",
      weight: "700",
      style: "italic",
    },
    {
      path: "../public/fonts/AILERON-REGULAR.OTF",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-aileron",
});

const optima = localFont({
  src: [
    {
      path: "../public/fonts/OPTIMA BLACK.OTF",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/OPTIMA BOLD OBLIQUE.OTF",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-optima",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
